modbus_status:
  - modbus_server_ip: "172.16.9.100"
    register: 1000
    interval: 1

cameras:
  - name: "Камера 4"
    camera_ip: "192.168.3.238"  # IP камеры
    rtsp: "rtsp://admin:kZx_vN8!@192.168.3.238/Streaming/Channels/101"
    index: 0                 # Уникальный индекс (1-3)
    min_tag_area: 300       # Минимальная площадь тега (пиксели)
    max_tag_area: 5000      # Максимальная площадь тега (пиксели)
    modbus:
      register: 1001           # Регистр Modbus для этой камеры
      modbus_server_ip: "172.16.9.100"