modbus_status:
  register: 1000
  modbus_server_ip: "192.168.17.23" # "172.16.9.14"

cameras:
  - name: "Камера 1"
    camera_ip: "192.168.17.86"  # IP камеры
    rtsp: "rtsp://admin:kZx_vN8!@192.168.17.86/stream1"
    index: 1                   # Уникальный индекс (1-3)
    modbus:
      register: 1001           # Регистр Modbus для этой камеры
      modbus_server_ip: "192.168.17.23" 

  #- name: "Камера 2"
  #  camera_ip: "10.16.9.53"
  #  rtsp: "rtsp://admin:kZx_vN8!@10.16.9.53/stream1"
  #  index: 2
  # modbus:
  #    register: 1002
  #    modbus_server_ip: "172.16.9.14" 

#  - name: "Камера 3"
#    camera_ip: "10.16.9.54"
#    rtsp: "rtsp://admin:kZx_vN8!@10.16.9.54/stream1"
#    index: 3
#    modbus:
#      register: 1003
#      modbus_server_ip: "172.16.9.14" 