modbus_status:
  - modbus_server_ip: "192.168.3.239"
    register: 0
    interval: 1

cameras:
  - name: "Камера 1"
    camera_ip: "192.168.3.238"
    snapshot_url: "http://192.168.3.238/ISAPI/Streaming/channels/101/picture?snapShotImageType=JPEG"
    username: "admin"
    password: "kZx_vN8!"
    index: 0
    interval: 0.25  # 250ms = 4 FPS
    timeout: 2
    max_tag_area: 50000
    modbus:
      register: 1
      modbus_server_ip: "192.168.3.239"