modbus_status:
  - modbus_server_ip: "192.168.17.23"
    register: 1000
    interval: 1
  - modbus_server_ip: "192.168.17.40"
    register: 1000
    interval: 1

cameras:
  - name: "Камера 1"
    camera_ip: "192.168.17.86"  # IP камеры
    rtsp: "rtsp://admin:kZx_vN8!@192.168.17.86/stream1"
    index: 1                   # Уникальный индекс (1-3)
    modbus:
      register: 1001           # Регистр Modbus для этой камеры
      modbus_server_ip: "192.168.17.23" 

  - name: "Камера 2"
    camera_ip: "192.168.17.87"  # IP камеры
    rtsp: "rtsp://admin:kZx_vN8!@192.168.17.87/stream1"
    index: 2                   # Уникальный индекс (1-3)
    modbus:
      register: 1002           # Регистр Modbus для этой камеры
      modbus_server_ip: "192.168.17.40" 

  - name: "Камера 3"
    camera_ip: "192.168.17.88"  # IP камеры
    rtsp: "rtsp://admin:kZx_vN8!@192.168.17.88/stream1"
    index: 3                   # Уникальный индекс (1-3)
    modbus:
      register: 1003           # Регистр Modbus для этой камеры
      modbus_server_ip: "192.168.17.40"