version: '3.8'

services:
  detector_april_tag:
    build: . # Сборка контенера
    network_mode: host
    image: 9221556df7ea # Использование уже имеющегося контенера
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./roi:/app/roi
      - ./logs:/app/logs
      #- /etc/localtime:/etc/localtime:ro для линукса

    environment:
      - QT_QPA_PLATFORM=offscreen
      - LOG_LEVEL_CONSOLE=DEBUG  # Уровень для консоли
      - LOG_LEVEL_FILE=INFO      # Уровень для файла
      - TZ=Asia/Krasnoyarsk  # Указываем явно временную зону
    restart: unless-stopped

