version: '3.8'

services:
  detector_april_tag:
    build: . # Сборка контенера
    network_mode: host
    #image: detector_april_tag # Использование уже имеющегося контенера
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./roi:/app/roi
    environment:
      - QT_QPA_PLATFORM=offscreen
    restart: unless-stopped

